source 'https://rubygems.org'

ruby File.read(".ruby-version").strip

gem 'acts_as_xlsx'
gem 'africastalking-ruby'
gem 'ahoy_matey'
gem 'awesome_rails_console', '~> 0.4.5'
gem 'aws-sdk', '~> 1'
gem 'axlsx','2.1.0.pre'
gem 'axlsx_rails'
gem 'bootstrap-colorpicker-rails'
gem 'bootstrap-sass'
gem 'carrierwave', '~> 2.2.2'
gem 'carrierwave-imageoptimizer'
gem 'coffee-rails'
gem 'devise'
gem 'execjs'
gem 'file_validators'
gem 'figaro'
gem 'fog'
gem 'froala-editor-sdk'
gem 'jquery-datatables-rails', '~> 3.4.0'
gem 'json'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mini_magick', '~> 4.5.0'
gem 'nprogress-rails'
gem 'postmark-rails'
gem 'pesapal'
gem 'pg', '~> 0.18'
gem 'rack-cors'
gem 'rails', '5.0.2'
gem 'rails_autolink'
gem 'rails_12factor'
gem 'rest-client'
gem 'rename'
gem 'roo'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubyzip','~>1.1.7'
gem 'seed_dump'
gem 'sendgrid-ruby'
gem 'tabs_on_rails'
gem 'travis'
gem 'turbolinks'
gem 'tzinfo-data', platforms: [:mingw, :mswin]
gem 'uglifier', '>= 1.3.0'
gem 'will_paginate'
gem 'wysiwyg-rails', '~> 2.6.0'
gem 'wicked_pdf', '~> 1.1'
gem 'wkhtmltopdf-binary'
gem 'whenever', require: false
gem 'zip-zip'

group :doc do
  gem 'sdoc', '~> 0.4.0'
end

group :development, :test do
  gem 'annotate'
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'rspec-rails', '~> 4.1', '>= 4.1.2'
end
